# Generated by Django 3.2.13 on 2024-09-12 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_auto_20240912_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='description',
            field=models.CharField(max_length=2000, verbose_name='Описание'),
        ),
    ]
