# Generated by Django 3.2.13 on 2024-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_alter_bookcard_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='authors',
            field=models.CharField(max_length=200, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='isbn',
            field=models.CharField(max_length=200, null=True, verbose_name='ISBN'),
        ),
    ]
