# Generated by Django 3.2.13 on 2024-09-12 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_auto_20240912_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcard',
            name='authors',
            field=models.CharField(max_length=500, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='description',
            field=models.CharField(max_length=3000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='isbn',
            field=models.CharField(max_length=500, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='bookcard',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название книги'),
        ),
    ]
